6 ajout dun objet prix sur chaque produit
dhammaorg/matta-nuu pull request #10
Opened 2024-08-26 14:01 UTC by Focus-Pacifique

Je tente la PR en mode draft.

J'ai normalement corrigé l'erreur que tu avais Sebastian, ainsi que tes suggestions.
Dis-moi si c'est mieux, et ce que l'on fait avec les dates dans l'historique des prix.

2024-08-26 14:49 UTC, seballot requested changes
Super merci pour ces avancées !!

J'ai fait quelques commentaires ;)

Concernant l'utilisation de l'historique des prix, je pense que ça sera utilisé le jour ou on fera des stats du genre "sur l'année dis moi le prix total de chaque produit". Mais ça faut voir avec les utilisateurs quels sont leur besoins réels.

La première utilisation qu'on pourra faire avec les prix c'est calculer le cout d'une recette par personne, et peut etre l'afficher dans la liste des recettes, comme ça tu peux voir quelles sont les plus chères

2024-08-26 14:49 UTC, seballot commented on src/views/products/ProductForm.vue
> +        this.savePrice()
If calling the method need a comment, it's likely than the method name is not good :) maybe rename it to preparePricesBeforeSave or something like this so it's self explanatory

2024-08-26 14:49 UTC, seballot commented on src/views/products/ProductForm.vue
> +        <label>Unit Price</label>
just "Price" is better I think, otherwise it can be confusing regarding the unit (piece, kg..)

2024-08-26 14:49 UTC, seballot commented on src/views/products/ProductForm.vue
> +        <Button icon=" pi pi-history" class="p-button-text"
this button could be included inside the above inputgroup, so we save one field

2024-08-26 14:49 UTC, seballot commented on src/views/products/ProductForm.vue
> +      this.visible = false
I don't think this modal should be closed upon price save

2024-08-26 14:49 UTC, seballot commented on src/views/products/ProductForm.vue
> +    getProductLastPrice(prices) {
J'ai peut etre mal regardé mais j'ai l'impression que cette methode n'est utlisé que dans `getLastPriceValue`, si c'est le cas autant fusionner les deux méthodes pour simplifier le code, y'aura juste à modifier la dernière ligne `return lastPrice.value || null`

2024-08-26 14:49 UTC, seballot commented on src/views/products/ProductsIndex.vue
> +          <InputText :value="getLastPriceValue(data)" disabled
why disable this input? it will probably be the most convenient way to enter all the prices :)

2024-08-26 14:49 UTC, seballot commented on src/views/products/ProductsPriceHistory.vue
> +                    <Calendar v-model="price.date" showIcon iconDisplay="input"
l'input calendar marche bien ailleurs, quand tu crée un évènement ou ajoute un note, donc bizarre que ça marche pas ici. Essaie peut etre avec `dateFormat="d MM yy"` comme pour ceux qui marchent? ou alors c'est que price.date est une string et pas une javascript date... A investiguer :)

2024-08-26 14:49 UTC, seballot commented on src/views/products/ProductsIndex.vue
> +  }
ce code est dupliqué. Il le sera probablement encore quand on devra calculer le prix d'une recette par example, donc ça serait mieux de trouver une manière de factoriser :) comme on a pas de classe "Product", c'est pas straighforward, mais quelques idées non testées

- créer un mixin
- mettre cette méthode dans le component root et comme ça tu pourra faire un truc genre `$root.getCurrentPriceFor(product)`
- Modifier l'objet Js product une fois qu'on le recoit depuis l'api pour modifier son prototype et ajouter une méthode (je sais pas si ça fonctionne)

2024-08-28 07:07 UTC, seballot commented on src/views/products/ProductsIndex.vue
> +  }
et aussi pour faciliter le calcul, peut etre toujours rangr les price history par ordre décroissant, comme ça le lastPrice c'est juste `pricesHistory[0]?.value`

2024-09-02 13:26 UTC, seballot commented
Top ! Merci pour les fix :)

Je pense que tu pourrais maintenant rajouter deux use case simple d'utilisation des prix

### Orders
rajouter dans les "Order" le prix total de la commande en utilisant les prix? (uniquement si au moins un des produits de la commande à un prix configuré, i.e. si le total est > 0) 
et aussi d'indiquer si certains produits de la commande n'ont pas de prix, par example
Estimated price: 2456€ [Warning Icon] <- on hover : 3 products do not have a price : Milk, Bread and Yogurt

### Recipie
Calculer le prix par personne d'une recette. On pourrait afficher ce prix dans la liste des recettes avec une nouvelle colonne? Avec le meme warning si tous les produits n'ont pas de prix

2024-11-07 22:16 UTC, Focus-Pacifique commented
Je crois qu j'ai fait une erreur : j'ai fait un git rebase, et maintenant je crois que les commit que j'ai fait veulent être merge avec master. Mais il me reste encore à calculer le prix par personne d'une recette

2024-11-12 14:00 UTC, seballot requested changes
Salut Alexis !

Merci d'avoir repris ce chantier :)

Autre truc qui ne fonctionne pas : quand on change le prix d'un produit, l'historique des prix se ne met pas à jour automatiquement. tu pourras aussi regarder ça stp?

Merci !

2024-11-20 11:52 UTC, Focus-Pacifique commented
> Autre truc qui ne fonctionne pas : quand on change le prix d'un produit, l'historique des prix se ne met pas à jour automatiquement. tu pourras aussi regarder ça stp?

Pour moi cela fonctionne. Peux-tu me préciser où cela ne fonctionne paspour toi ?

2024-11-20 16:34 UTC, Focus-Pacifique commented
J'ai ajouté les prix dans la liste des recettes, ainsi que dans le détail des recettes.

Une fois les bugs éventuels corrigés, ou bien si tu veux que je modifie des choses, pour moi la PR sera terminée.

2024-11-22 15:44 UTC, Vichearith commented
Je vois avec JF s'il peut trouver quelqu'un qui connait bien Matta Nuu.
*Eric ROS*


Le jeu. 21 nov. 2024 à 08:55, Sebastian Castro ***@***.***> a
écrit :

> Ok cool ! @ousabd <https://github.com/ousabd> @Vichearith
> <https://github.com/Vichearith> vous voulez bien tester les nouvelles
> features de Alexis sur les prix?
>
> Vous pouvez tester à cette adresse
> https://deploy-preview-10--matta-nuu.netlify.app/#/
>
> Ca utilise la meme DB que en prod, donc soit utilisez le compte de Dhamma
> Mahi avec prudence, soit utilisez ***@***.*** / behappy ou
> ***@***.*** / behappy
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dhammaorg/matta-nuu/pull/10#issuecomment-2490307051>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADVMFBWTYPBYEFIH6SLPLOT2BWGXRAVCNFSM6AAAAABNECTWVGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJQGMYDOMBVGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-27 19:07 UTC, ThibaudLk commented
Salut le Dhamma dev crew, je suis en ce moment à Dhamma Mahi en long terme à la cuisine donc si besoin de tester des fonctionnalités sur place je peux m'en occuper !
Ptet Alexis si on peut s'appeler pour que tu m'expliques la fonctionnalité ?

2024-11-28 10:54 UTC, Focus-Pacifique commented
Nathalie qui est long terme au centre, et à l'intendance, s'occupe de tester. Elle m'a déja à fait des retours, j'ai quelques trucs a modifier.

2024-12-28 13:32 UTC, Focus-Pacifique commented
@seballot Pour moi la PR est prête maintenant.

2024-12-28 15:35 UTC, seballot commented on src/App.vue
> +    isSameDay(date1, date2) {
Yop ! y'a déjà des méthode équivalente ici : https://github.com/dhammaorg/matta-nuu/blob/7892671faa1b34a20bb64249038bf9e1bb3d0c18/src/services/utils.js#L22

equals et isTodayOrAfter

2026-05-04 20:03 UTC, seballot commented
Salut !

Pour info j'étais à Suriyarama la semaine dernière et j'ai fait plusieurs améliorations sur Matta-Nuu. J'ai incroporé tes changement Alexis, en les retravaillant un peu. Je ferme donc cette PR :)

2026-05-04 20:03 UTC, closed without merging